Marching squares config map
Chainsawkitten/PhotoGeo pull request #53
Opened 2018-03-14 13:06 UTC by LarsIngo

Fix #51

2018-03-14 13:25 UTC, Chainsawkitten requested changes

2018-03-14 13:25 UTC, Chainsawkitten commented on src/tracing/marching_squares.cpp
> +#include <iostream>
Not used.

2018-03-15 14:02 UTC, LarsIngo commented on src/tracing/marching_squares.cpp
> +#include <iostream>
iostream removed, assert is still used

2018-03-15 14:26 UTC, Chainsawkitten approved these changes

2018-03-15 14:36 UTC, merged